paper_info: datasets/sample/paper_info.csv
reviewer_info: datasets/sample/reviewer_info.csv
constraints: datasets/sample/constraints.csv
similarity_scores: datasets/sample/similarity_scores.csv
bid_scores: datasets/sample/bid_scores.csv
output_dir: results/sample/exp1
algo_name: RAMP
2stage: false
optimize_sampling: true
maxprob: 0.9
beta: 0.1
reward_region: 0.05
pen_coauthor: 0.2
pen_2cycle: 0.1
